using System;
using System.Reflection;
using System.Runtime.InteropServices;

// Shared Assembly info: it must be added as a link to
// each project.
// It contains information that must be the same for all
// assemblies produced by this solution.

[assembly: AssemblyCompany( "Invenietis" )]
[assembly: AssemblyProduct( "SimpleGitVersion" )]
[assembly: AssemblyCopyright( "Copyright © Invenietis 2015" )]
[assembly: AssemblyTrademark( "" )]
[assembly: AssemblyCulture( "" )]
[assembly: CLSCompliant( true )]
[assembly: ComVisible( false )]

#if DEBUG
    [assembly: AssemblyConfiguration("Debug")]
#else
    [assembly: AssemblyConfiguration( "Release" )]
#endif

// 0.1.0 ==> Ordered Version = 1300140001, File = 0.0.19838.36833
// 0.1.1 ==> Ordered Version = 1300270002, File = 0.0.19840.35762
// 0.1.2 ==> Ordered Version = 1300400003, File = 0.0.19842.34691
// 0.2.0 ==> Ordered Version = 2600150001, File = 0.0.39675.9201
// 0.2.1 ==> Ordered Version = 2600280002, File = 0.0.39677.8130
// 0.3.0-rc ==> Ordered Version = 3900150001, File = 0.0.59511.37105 (last manually generated)
[assembly: AssemblyVersion( "0.3" )]
[assembly: AssemblyInformationalVersion( "0.3.0-rc" )]
[assembly: AssemblyFileVersion( "0.0.59511.37105" )]

[assembly: SimpleGitVersionInfo( "0.3.0-rc", "2015-08-22 17:30:00Z", "manual" )]
/// <summary>
/// Automatically generated by SimpleGitVersionTask 0.2.0. 
/// </summary>
class SimpleGitVersionInfoAttribute : Attribute
{
    public SimpleGitVersionInfoAttribute( string semVer, string buildTimeUtc, string sgvVersion )
    {
        SemVer = semVer;
        BuildTimeUtc = buildTimeUtc;
        SGVVersion = sgvVersion;
    }

    public readonly string SemVer;
    public readonly string BuildTimeUtc;
    public readonly string SGVVersion;

    public override string ToString()
    {
        return String.Format( "SemVer: {0}, BuildTimeUtc: {1}, SGVVersion: {2}", SemVer, BuildTimeUtc, SGVVersion );
    }
}
